name: Build CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkita64

    steps:
    - uses: actions/checkout@v4
    
    - run: |
           cd emummc
           chmod 755 build.sh
           ./build.sh

    - name: Upload Binary
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: |
              emummc/emummc.kipm
